# Generated by Django 5.1.4 on 2024-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_slot_number', models.IntegerField(help_text='Parking Slot Number')),
                ('student_name', models.CharField(help_text="Student's Name", max_length=200)),
                ('registration_plate', models.CharField(blank=True, help_text='Registration Plate Number', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('nr_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending'), ('ApprovedPending', 'approvedPending')], default='pending', help_text='Request Status (approved/denied/pending/approvedPending)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='Available', max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_plate', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
