# Generated by Django 4.2.17 on 2024-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('username', models.CharField(max_length=150)),
                ('room_nr', models.IntegerField()),
            ],
            options={
                'unique_together': {('time_frame', 'date')},
            },
        ),
    ]
