# Generated by Django 5.1.3 on 2024-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0002_remove_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
