# Generated by Django 5.1.3 on 2024-11-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0003_rename_user_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='User',
        ),
    ]
