# Generated by Django 5.1.3 on 2024-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0004_rename_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student')], default='Student', max_length=10),
        ),
    ]
